steps:
  - label: Build and Upload to TestFlight
    branches: "main"
    command: .buildkite/commands/build-and-upload-to-testflight.sh
    plugins:
      - automattic/a8c-ci-toolkit#3.4.2
      - automattic/nvm#0.3.0
    agents:
      queue: mac
    env:
      IMAGE_ID: xcode-15.4
    artifact_paths:
      - "ios/App/build/Blocknotes.ipa"
      - "ios/App/build/Blocknotes.app.dSYM.zip"
